name: Build for Linux

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.20.2
      - name: Build
        run: go build -o filetype
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: filetype
          path: ./filetype
